### ISSUE TITLE
Rendering problems in recent versions

### ISSUE THREAD

**Issue by MrSystem** [adobe-fonts/source-sans-pro#151]
I am experiencing some rendering problems in the latest version.

Compare non-variable fonts v2.020-1.075 to v2.040-1.090:
[2.020-1.075](https://user-images.githubusercontent.com/16069471/47823823-47763080-dd6a-11e8-91a6-d9c04d629132.png)
[2.040-1.090](https://user-images.githubusercontent.com/16069471/47823824-47763080-dd6a-11e8-86be-3d62b5edbbf9.png)

The letters in the older version are more defined than those in the newer version (e.g. look at the '-' character).

I experienced the same problem when using variable fonts v2.020-1.075.

Also, is it by-design that letters in variable and non-variable fonts of the same size [have different width](https://user-images.githubusercontent.com/16069471/47823825-47763080-dd6a-11e8-82ac-3cc9b516f01f.png)?

**Comment by miguelsousa** [comment]
@MrSystem thanks for the report. You didn't mention what font format you used for making the screenshots, but I'm going to guess they were made with the TrueType (.ttf) fonts rather than the OpenType-CFF (.otf). The new TTFs are not hinted, so that explains the reduction of the crispiness of glyph edges of the newer version. We'll look into addressing this.

As for the spacing of variable vs. non-variable styles it should be exactly the same. See below the screenshots I made with [FontView](https://github.com/googlei18n/fontview/releases). I'd attribute the difference you're getting to the way the browser(?) is computing the fractional positions of the glyphs on the line.

<img width="835" alt="sourcesansvariable-roman otf" src="https://user-images.githubusercontent.com/2119742/47825040-204d3e00-dd2d-11e8-9e11-b82cae62a35f.png">
<img width="835" alt="sourcesansvariable-roman ttf" src="https://user-images.githubusercontent.com/2119742/47825047-25aa8880-dd2d-11e8-96b3-b95e12e7c248.png">
<img width="835" alt="sourcesanspro-regular ttf" src="https://user-images.githubusercontent.com/2119742/47825052-2b07d300-dd2d-11e8-8fbf-cc2230aed439.png">
<img width="835" alt="sourcesanspro-regular otf" src="https://user-images.githubusercontent.com/2119742/47825059-30651d80-dd2d-11e8-99a1-54d7243ca5c1.png">

**Comment by MrSystem** [comment]
Indeed I used TrueType fonts to make all screenshots. Alright then, I'm waiting for hinted versions to be released.

I used Microsoft WordPad to make the third screenshot.
I verified the problem is not reproduced in Word and Firefox, but it is in Paint, so it could well be a bug in a Windows library. You may want to test it out anyway.

**Comment by fitojb** [comment]
No idea why would you intentionally release a TTF font (whose design was especifically touted as suitable for UIs, BTW) with known visual regressions. The lack of hinting blocks LibreOffice from updating to this version.

I thought tools like ttfautohint were supposed to help with costly/time-consuming hinting work?

**Comment by FloraCanou** [comment]
> The lack of hinting blocks LibreOffice from updating to this version.

Hmmm. That's an opportunity for LibreOffice to turn to OTF, isn't it?

**Comment by miguelsousa** [comment]
> No idea why would you intentionally release a TTF font (whose design was especifically touted as suitable for UIs, BTW) with known visual regressions.

And it remains suitable for UIs, even in its unhinted form. The degree to which environments require fonts to be hinted varies immensely, even within the same platform (e.g. Win7 vs. Win10). macOS for example disregards the hinting data entirely.

Just because a font is hinted is not by itself a guarantee that it will render any better; it all depends on many factors. My point is, what you perceive as "known visual regressions" is your personal assessment which is based on your conditions, none of which are universal.

> I thought tools like ttfautohint were supposed to help with costly/time-consuming hinting work?

Using **ttfautohint** has been on our plans all along, as we have no desire to spend any more of our time hand-hinting TT glyphs. But given the improvements we've seen in hardware and software since the last release (September 2015), we wanted to assess how much people still care about hints on TT fonts and to what degree they —the hints— are still necessary. For example, the latest version of [Source Serif](https://github.com/adobe-fonts/source-serif-pro) released in August (over 2 months ago) also includes unhinted TTFs, and no one has yet opened an issue about it.

That said, the next step on our plans is indeed to put the TTFs thru ttfautohint. But be warned that's as far as we'll go with the effort of hinting that font format.

**Comment by fitojb** [comment]
Good to hear you do plan to leverage ttfautohint.
