### ISSUE TITLE
Add Cyrillic support

### ISSUE THREAD

**Issue by mvasilkov** [adobe-fonts/source-sans-pro#6]
Please pretty please :3

**Comment by jameswilson** [comment]
How can we go about getting Google's hosted font to add a `&subset=cyrillic-ext`  and `&subset=greek-ext`?

**Comment by pauldhunt** [comment]
AFAIK, Google will not do this until all fonts in the family support Greek/Cyrillic. This means that they will not add the Source Sans fonts until after the italic fonts are also updated with Greek/Cyrillic characters.

**Comment by davelab6** [comment]
Paul is correct, let me know if you have any questions :)

**Comment by jameswilson** [comment]
Thanks @pauldhunt @davelab6,  I've gone about creating a custom subset for Greek and Cyrillic. Now comes the hard part of figuring out what to include/exclude from the subsets.

**Comment by davelab6** [comment]
https://github.com/davelab6/pyfontaine/tree/master/fontaine/charmaps has
some examples

**Comment by davelab6** [comment]
@jameswilson how did you get on? :)

**Comment by pauldhunt** [comment]
@jameswilson what are you trying to accomplish?

**Comment by jameswilson** [comment]
@pauldhunt  since Google won't host the updated Source Sans Pro until the italics is implemented, and my site doesn't use italics, I'm trying to make a subset for Greek and a subset for Cyrillic language using what you currently have built.

@davelab6 I've got it working now, I ended up using [Fontie](http://fontie.flowyapps.com/home) which has easy checkbox options to generate cyrillic or greek subsets. I also tried using the "Expert" panel on [FontSquirrel's Webfont Generator](http://www.fontsquirrel.com/tools/webfont-generator) to select Cyrillic / Greek languages for building a custom subset, but It totally messed up the EOT files so this was a no-go for Internet Explorer.   Sadly, Fontie doesn't produce woff2, so after using fontie, i had to take the resulting TTF from fontie and pass it through an online [ttf-to-woff2 converter](http://everythingfonts.com/ttf-to-woff2).

Last but not least, I uncovered a nice IE bug that breaks when using multiple weights for the same font-family name in @font-face declarations.  It looks like there is no way around that except to use different font-family names -- but it appears Google Fonts itself doesn't even support this  ([bug](https://code.google.com/p/googlefontdirectory/issues/detail?id=9)). 

When the production release goes live, I'll send you guys a link. Thanks guys.

**Comment by pauldhunt** [comment]
@jameswilson what do you mean by ‘Cyrillic language’? Russian? Ukrainian? Bulgarian? Russian + Ukrainian? ???

**Comment by jameswilson** [comment]
Oops, s/language/characters.

**Comment by azamat-sharapov** [comment]
regular cyrillic looks good, but italic is ugly :( 
(on Ubuntu 14.04.1)

**Comment by Fitoschido** [comment]
> regular cyrillic looks good, but italic is ugly :(

Which is nonsense. If you have read this thread more carefully, you would have noticed Cyrillic italics are not yet released. So you’re actually seeing glyphs substituted from another font.

**Comment by davelab6** [comment]
Or autoslanted, which looks bad

**Comment by azamat-sharapov** [comment]
@Fitoschido I know that it is not released, I read thread already and not only this thread. Why do you think, that my words are nonsense? Did anybody ask you is it nonsense or not? or you like putting your nose anywhere you want?

**Comment by pauldhunt** [comment]
@azamat-sharapov how can a nonexistent italic look ugly? or in other word, please explain yourself.

**Comment by azamat-sharapov** [comment]
@pauldhunt I'll better remove an inappropriate comment of mine. Looking forward for new releases with italic support though. Thanks.
