### ISSUE TITLE
otf / ttf hinting inconsistencies question

### ISSUE THREAD

**Issue by Pomax** [adobe-fonts/source-sans-pro#62]
Based on https://github.com/adobe/brackets/pull/8985#issuecomment-81507709 it appears that the ttf and otf fonts have drastically different hinting going on, raising the question "which one looks as intended" for the purposes of using the fonts for stable UIs. Is the otf authoritative, and the ttf likely to see improvements/adjustments to its conversion as time goes on?

**Comment by pauldhunt** [comment]
The issue here is that different environments use different font rasterizers. If your targeted environment has good support for PostScript type hinting, you will probably want to use the OTF fonts. If, on the other hand, your targeted environment does not have good support for PS type hinting, you may prefer the TTF font versions and this is the reason for their existence. If you do not know what hinting your targeted environment rasterizer supports, you will want to test for yourself and make a judgement on the suitability of each format.

**Comment by peterflynn** [comment]
@pauldhunt To clarify, we're actually talking about the WOFF versions of the font -- differences between the .ttf.woff and .otf.woff copies.  But I guess the WOFF copies are just thin wrappers around the TTF and OTF originals?

.ttf.woff:
![ttf woff](https://cloud.githubusercontent.com/assets/1197510/6673962/e7bae772-cbd3-11e4-88aa-6ae4cc6b93ae.png)

.otf.woff:
![otf woff](https://cloud.githubusercontent.com/assets/1197510/6673963/e7bfc2ba-cbd3-11e4-97e2-cd8f95c67e1e.png)

In the second image, the characters look vertically stretched ~1px (e.g. look at "o" or "m"/"n"), and the weight is heavier.

In this case the environment in question is basically Chrome 39, which uses DirectWrite on Windows.  But I couldn't find good info online about how well DirectWrite supports PotScript hinting...

**Comment by miguelsousa** [comment]
To add to Paul's comment, when we hint the fonts we make no effort to match the rasterization of both formats pixel-by-pixel, because that would be close to impossible anyway.

The glyph outlines are the exact same size on both formats; any differences you see in terms of size and proportions at small rendered sizes are in big part the result of different rasterization algorithms, which the font is not in control of.

**Comment by miguelsousa** [comment]
> But I guess the WOFF copies are just thin wrappers around the TTF and OTF originals?

Correct.

> In this case the environment in question is basically Chrome 39, which uses DirectWrite on Windows. But I couldn't find good info online about how well DirectWrite supports PotScript hinting...

DirectWrite has very good support for PostScript hinting; it's lightyears better than GDI.

If one of Brackets' goals is to be cross-platform pixel-by-pixel, your best bet is to standardize on the OTF fonts. This is because DirectWrite uses Adobe's CFF rasterizer, which now happens to be open source. The Mac platform uses its own rasterization technology, but I expect that the OTFs will render more similarly between Mac & Windows than the TTFs ever will.

**Comment by Pomax** [comment]
I did not know the rasterizer was now open source - that's amazing news!

**Comment by miguelsousa** [comment]
@Pomax We announced it in May 2013. I'm surprised it's the first time you hear about it.

**Comment by twardoch** [comment]
I'll just add for clarification: it's part of FreeType.

**Comment by Pomax** [comment]
That's... very odd, I'm pretty sure I was on the opentype list well before then. Oh well, still great news, I'm just late to the party =)
