### ISSUE TITLE
Sizing issue - any fallback fonts recommended?

### ISSUE THREAD

**Issue by mydigitalself** [adobe-fonts/source-sans-pro#63]
Hi there,

At Gitter, we recently switched over to Source Sans Pro, which we really love. One of the issues we've had, however, is there's quite a substantial size difference between Source Sans Pro and other fonts. Our app does some fairly nifty things on load to force the browser to the bottom of the chat and we get some timing race conditions and due to the sizing of Source Sans Pro we often get a reflow of content.

We've tried using events once the font is loaded to then force the chat to the bottom of the page, but this makes for an unpleasant flicker of the user interface.

We were wondering if there were any standard Mac/Windows fonts that have the same sizing?

To Illustrate my point, here's a series of fonts at 14pt...
![screen shot 2015-05-27 at 14 09 45](https://cloud.githubusercontent.com/assets/1491887/7836703/31575436-047a-11e5-9c27-643d110e418e.png)

**Comment by forcebold** [comment]
Hi Mike,
Let me see if I understand. Your CSS stack has Source Sans Pro and `sans-serif`. The latter defaults to Helvetica on Mac, and to Arial on Windows. SSP has an apparent smaller size (i.e. it's smaller on the body) than Helvetica or Arial, so you bump up the value of the font size to compensate for that. This in turn creates a reflow when SSP loads, because the layout is initially rendered using the metrics of the fallback fonts (Helvetica & Arial). Is that it?

**Comment by miguelsousa** [comment]
Hi Mike,
Let me see if I understand. Your CSS stack has Source Sans Pro and `sans-serif`. The latter defaults to Helvetica on Mac, and to Arial on Windows. SSP has an apparent smaller size (i.e. it's smaller on the body) than Helvetica or Arial, so you bump up the value of the font size to compensate for that. This in turn creates a reflow when SSP loads, because the layout is initially rendered using the metrics of the fallback fonts (Helvetica & Arial). Is that it?

**Comment by mydigitalself** [comment]
That's pretty much exactly it Miguel.

**Comment by miguelsousa** [comment]
OK. I don't think that trying to find a fallback font with the same apparent size as SSP is the best way to go about it, because you'll always be at the mercy of `sans-serif`, which you won't have any control over. You mentioned that you're already using events, and I assume that you're doing that to prevent any page rendering until SSP is fully loaded. I don't have any experience with that, so I can't really say if any of it could be optimized. So my suggestion if for the UI to use the font size that is right for Source Sans to begin with. I understand that will make the fallback look too big, but how much do you really need to care about that? Aren't all users going to see only Source Sans anyway?

**Comment by mydigitalself** [comment]
We don't use events to stop the page displaying entirely, we don't want to block on font load. What I was saying is that we tried using the event and then forcing the page to the bottom again but it caused additional flicker.

What we ended up finding is that PT Sans (Mac) and Calibri (Windows) were pretty closely sized fallbacks and so use those with `sans-serif` being the final fallback. If anyone else experiences this, I'd suggest using those two.

**Comment by mydigitalself** [comment]
Out of curiosity, why such the big discrepancy in sizing? It seems almost a 2pt difference to the untrained eye.

**Comment by moyogo** [comment]
This is a design decision. Some fonts have taller x-height than others for better legibility at small sizes. Source Han Sans actually has a taller x-height, so you could subset it if that’s what you need.

This is also what [font-size-adjust](http://www.w3.org/TR/css3-fonts/#font-size-adjust-prop) is for. Unfortunately, it’s only supported in Firefox ([caniuse](http://caniuse.com/#search=font-size-adjust)).

**Comment by mydigitalself** [comment]
Thanks for the info @moyogo will keep an eye on `font-size-adjust`

**Comment by pauldhunt** [comment]
The sizing discrepancy that you're seeing is probably a consequence of my trying to be too ambitious with the brief for this design. In addition to being legible in UI environments, I also wanted the typeface to function well in running text. To achieve the latter, I gave the ascenders and descenders more 'bookish' proportions (making them longer). When you have to fit a typeface with long extenders (SSP) into the same space as one with shorter ones (Helv/Arial) you basically have to shrink down all the letters (even though the x-height is rather large relative to the cap height). If browsers ever let you spec type by x-height size this would probably be less noticeable of an issue, but web typography controls have a long way to go yet. Maybe I was too forward-thinking? :^p
