### ISSUE TITLE
woff2 in main 2.010 distribution?

### ISSUE THREAD

**Issue by albell** [adobe-fonts/source-sans-pro#66]
For non-experts, it would be really useful to include woff2 files in the main distributions, and woff2 `src`s in the main CSS file.

I don't know the pros and cons of the various converters. I don't really have money to spend on pro font tooling. I want to send the smallest possible files on the wire. I'm sure there are many people just like me. In my very limited understanding, WOFF2 seems to be widely considered <a href="https://css-tricks.com/snippets/css/using-font-face/">best practice</a> on the web.

If I'm missing something obvious please enlighten me, and thanks for a beautiful product.

**Comment by miguelsousa** [comment]
Try [these files](https://github.com/adobe-fonts/source-sans-pro/releases/download/woff2/WOFF2.zip) and let us know how it goes.

**Comment by baloneysandwiches** [comment]
Thank you. Works great. Quick questions:

- Can you maybe put that link up in the master readme for the next guy/gal?

- For web work are there subtle functional or compatibility differences between an "otf.woff" and a "ttf.woff"? I thought WOFF and WOFF2 were their own distinct formats. Is it more like a compression layer?

- In that link, why are the "otf.woff2" files significantly larger that the "ttf.woff2" files? I thought OTF allowed cubic bezier curves instead of just quadratic bezier, which would be typically space-saving. Generally it's supposed to be the other way around, right?

**Comment by twardoch** [comment]
1. The belief that the "naked" cubic outlines are space-saving as opposed to quadratics is a widespread myth that has little support in reality. The old SVG Font format, which can represent both quadratic and cubic glyphs (even in the same font) in plain text offers a common ground for comparison. If I convert an OTF of Source Sans Pro Regular into SVG, it’ll be about 1.1 MB, while an SVG made out of a TTF is 1.2 MB. So the difference is quite small. This is because quadratics use more on-curve points but less off-curve points while cubic use less on-curve points but more off-curve points. So it kind of balances each other out (the cubics are about 8% smaller but that’s it). 

2. In OpenType, cubics are stored in a "CFF" font table (in an OTF font) and quadratics are stored in a "glyf" table (in a TTF font). The "glyf" table is completely linear, very straightforward and uses almost no compression. The "CFF" table on the other hand uses extensive compression by itself. In a way, you could say that that TTFs are not compressed while OTFs are already compressed. 

3. WOFF2 applies a very aggressive modern compression algorithm (Brotli) which is much more effective than the built-in OTF compression. If you convert a TTF into WOFF2, the flat "glyf" table gets compressed very efficiently using Brotli, but if you convert an OTF into WOFF2, then the Brotli compression does not yield much saving (or even none) for the "CFF" table, because that table is already compressed. 

So, since the new WOFF2 Brotli is more effective than the old CFF compression, .ttf.woff2 often end up smaller than the .otf.woff2.

**Comment by baloneysandwiches** [comment]
@twardoch  Thank you, very illuminating. Is there any compatibility or feature set reason to not just use the smaller "ttf.woff2" then? For modern evergreen browsers, is there any scenario in which an author would prefer the slightly larger "otf.woff2" file?

**Comment by twardoch** [comment]
Well, OTF-based or TTF-based fonts (regardless of whether they’re “naked” or in WOFF or WOFF2) render differently in small sizes on systems that use hinting, a font-internal mechanism that tells the system how to optimize the fonts on small screen sizes. On Mac OS X, iOS and newer Android versions, you won’t see much difference, but on Windows, you will. The older the Windows, the more difference. The differences won’t be seen in larger sizes but they will be in small sizes. If you target a particular minimal OS, just make a test page comparing the OTF- and TTF-based WOFF2 in a few small sizes and see if you prefer any of these variants. It’s not possible to say upfront, in general, which one will look better.

**Comment by mattez** [comment]
I made basic [test of Font Size vs Font Weight](https://codepen.io/mattez/full/pdxBJG/) on CodePen.
Screen shot of this test is attached.

Font source: Google Fonts.
Browsers:
Google Chrome last version - use **WOFF2**
Old Safari 8.0.8 - use [TTF]

![source-sans-pro-issue-01](https://user-images.githubusercontent.com/143115/33382593-7143528c-d521-11e7-9985-1da0b65c8ff7.png)
![source-sans-pro-issue-02](https://user-images.githubusercontent.com/143115/33382594-71628238-d521-11e7-8ebd-88554f0628b8.png)
