### ISSUE TITLE
Is it possible to create a small capital only font with trivial effort?

### ISSUE THREAD

**Issue by notcome** [adobe-fonts/source-sans-pro#69]
Is there some type of indexing file I could hack? I need this in certain legacy softwares.

Thank you!

**Comment by moyogo** [comment]
https://github.com/twardoch/fonttools-utils has a tool called pyftfeatfreeze that can do that.

**Comment by notcome** [comment]
@moyogo Thanks! It works great. Though I am still wondering if I could construct such fonts using makeotf.

**Comment by twardoch** [comment]
Tou can. My tool only modifies the cmap table, ie. the mapping of glyphs to Unicodes. With makeotf, you can supply an GOADB file (or something like that) which AFAIR has three columns: the original glyph name, the final font's glyph name and the associated Unicode. So you can make a GOADB file yourself which goes something like this (typing from memory): 

A.sc A uni0041

and so on. The resulted font will have the glyph "A.sc" renamed to "A" and mapped to Unicode U+0041 (Latin capital letter A). Which is in essence what you want. 

Since Source is published under OFL, remember that if you publish your custom-built fonts, the names (family names, full names, PostScript names) of the fonts may not include the names declared as Reserved Font Names for the font. This can be controlled via the "name" table section of the FEA file.

**Comment by miguelsousa** [comment]
> three columns: the original glyph name, the final font's glyph name and the associated Unicode

Column 1 and 2 are swapped.
