### ISSUE TITLE
Polish (and maybe other glyphs) wrong size in WOFF2

### ISSUE THREAD

**Issue by lxg** [adobe-fonts/source-sans-pro#80]
I have realized that when converting Source Sans Pro to WOFF2, some Polish glyphs appear larger or smaller than the plain latin ones.

I have realised this after downloading Source Sans Pro from openfontlibrary.org and creating webfonts with Font Squirrel (“optimal” settings).

It can be reproduced with Google Fonts. See the following JSfiddle:

http://jsfiddle.net/Lkjvtb32/

Strangely, in the fonts created with Font Squirrel, the Polish glyphs are *smaller* than the plain latin ones. See an example:

https://free.tixys.com/testshop (switch to Polish).

When increasing/decreasing the font-size of the “Dokąd chcesz podróżować?” paragraph, sometimes the text appears ok, but at roughly every second font size it looks wrong.

I hope I’m not barking up the wrong tree here, but as it can be reproduced with two independent font providers, I thought this might be a problem with the font itself.

Tested with recent Firefox and Chromium on Linux.

**Comment by twardoch** [comment]
They're different because they're coming from a different font. By default, Google Fonts and other webfont providers subset the fonts by limiting the character set to reduce their file size. The default subsets usually correspond to what used to be called "Western" -- the basic English alphabet plus diacritics for French, German, Swedish, Spanish but not Czech, Polish or Hungarian. 

To get the larger subsets, you need to customize your webfont requests. For example, with Google Fonts, you need to add "&subset=latin-ext,latin" to the font request URL. In Font Squirrel, customize the subset in the advanced settings. 

26 years after the fall of the iron curtain, it's still doing very well in the font world :) 

Best,
Adam

**Comment by twardoch** [comment]
Ps. If a subsetted webfont does not include a given character, the next font specified in the CSS font-family property, or the default browser font, is used to render it. So if your font-family says "Source Sans Pro, Arial but Source Sans Pro is served as a Western-only subset, Arial is used to render the ą and ż like in your jsfiddle example.

**Comment by lxg** [comment]
Oh well, that’s really a shame. I tested the JSfiddle with `latin-ext`, and that “fixes” the issue indeed. As for Font Squirrel, I thought by “Western” they meant all latin based scripts (i.e. all non-Arabic/Asian etc.). I’ll create a new export and expect it to be fixed there, too. Sorry for the invalid bug report!

**Comment by twardoch** [comment]
No no, Poland still is "Eastern Europe" :D
