### ISSUE TITLE
Heavier than Black

### ISSUE THREAD

**Issue by Astrinus** [adobe-fonts/source-sans-pro#88]
Hello!
   I'd be very grateful if you can provide an ExtraBlack weight, maybe a bit lighter than Arial Black (which I want to replace).

**Comment by pauldhunt** [comment]
@Astrinus I agree this is a great idea. Are you able to help out with this in any way?

**Comment by Astrinus** [comment]
I'm not a designer (actually, I'm quite clumsy at artistic drawing & co.), nor I ever made a font, but I have a strong background in programming. If you can tell me what I could do (for example extrapolating from current weights, if possible, maybe just for doing 90% of the work) and point me to some resources (programs, file format, etc.), I'd be willing to help.

**Comment by pauldhunt** [comment]
@Astrinus Extrapolating the weight is quite easy and represents .01% of actual work on such a project. I’ve already done some experiments in this. Unfortunately, the majority of the work in such a project would involve finessing the extrapolated outlines so that they look as good as the other styles.

**Comment by Astrinus** [comment]
You see, I have no idea how to build a font, but I'm willing to help in any way I can. Just tell me how ;-)

**Comment by pauldhunt** [comment]
@Astrinus Unfortunately, the only way to help in this area would be to do actual work on the font sources. This would require you to get set up with font editing software capable of making the adjustments needed.
